export const cards = [
  {
    id: 1,
    name: "ace_of_clubs",
    score: 1,
    img: "ace_of_clubs.png",
  },
  {
    id: 2,
    name: "ace_of_diamonds",
    score: 1,
    img: "ace_of_diamonds.png",
  },
  {
    id: 3,
    name: "ace_of_hearts",
    score: 1,
    img: "ace_of_hearts.png",
  },
  {
    id: 4,
    name: "ace_of_spades",
    score: 1,
    img: "ace_of_spades.png",
  },
  {
    id: 5,
    name: "2_of_clubs",
    score: 2,
    img: "2_of_clubs.png",
  },
  {
    id: 6,
    name: "2_of_diamonds",
    score: 2,
    img: "2_of_diamonds.png",
  },
  {
    id: 7,
    name: "2_of_hearts",
    score: 2,
    img: "2_of_hearts.png",
  },
  {
    id: 8,
    name: "2_of_spades",
    score: 2,
    img: "2_of_spades.png",
  },
  {
    id: 9,
    name: "3_of_clubs",
    score: 3,
    img: "3_of_clubs.png",
  },
  {
    id: 10,
    name: "3_of_diamonds",
    score: 3,
    img: "3_of_diamonds.png",
  },
  {
    id: 11,
    name: "3_of_hearts",
    score: 3,
    img: "3_of_hearts.png",
  },
  {
    id: 12,
    name: "3_of_spades",
    score: 3,
    img: "3_of_spades.png",
  },
  {
    id: 13,
    name: "4_of_clubs",
    score: 4,
    img: "4_of_clubs.png",
  },
  {
    id: 14,
    name: "4_of_diamonds",
    score: 4,
    img: "4_of_diamonds.png",
  },
  {
    id: 15,
    name: "4_of_hearts",
    score: 4,
    img: "4_of_hearts.png",
  },
  {
    id: 16,
    name: "4_of_spades",
    score: 4,
    img: "4_of_spades.png",
  },
  {
    id: 17,
    name: "5_of_clubs",
    score: 5,
    img: "5_of_clubs.png",
  },
  {
    id: 18,
    name: "5_of_diamonds",
    score: 5,
    img: "5_of_diamonds.png",
  },
  {
    id: 19,
    name: "5_of_hearts",
    score: 5,
    img: "5_of_hearts.png",
  },
  {
    id: 20,
    name: "5_of_spades",
    score: 5,
    img: "5_of_spades.png",
  },
  {
    id: 21,
    name: "6_of_clubs",
    score: 6,
    img: "6_of_clubs.png",
  },
  {
    id: 22,
    name: "6_of_diamonds",
    score: 6,
    img: "6_of_diamonds.png",
  },
  {
    id: 23,
    name: "6_of_hearts",
    score: 6,
    img: "6_of_hearts.png",
  },
  {
    id: 24,
    name: "6_of_spades",
    score: 6,
    img: "6_of_spades.png",
  },
  {
    id: 25,
    name: "7_of_clubs",
    score: 7,
    img: "7_of_clubs.png",
  },
  {
    id: 26,
    name: "7_of_diamonds",
    score: 7,
    img: "7_of_diamonds.png",
  },
  {
    id: 27,
    name: "7_of_hearts",
    score: 7,
    img: "7_of_hearts.png",
  },
  {
    id: 28,
    name: "7_of_spades",
    score: 7,
    img: "7_of_spades.png",
  },
  {
    id: 29,
    name: "8_of_clubs",
    score: 8,
    img: "8_of_clubs.png",
  },
  {
    id: 30,
    name: "8_of_diamonds",
    score: 8,
    img: "8_of_diamonds.png",
  },
  {
    id: 31,
    name: "8_of_hearts",
    score: 8,
    img: "8_of_hearts.png",
  },
  {
    id: 32,
    name: "8_of_spades",
    score: 8,
    img: "8_of_spades.png",
  },
  {
    id: 33,
    name: "9_of_clubs",
    score: 9,
    img: "9_of_clubs.png",
  },
  {
    id: 34,
    name: "9_of_diamonds",
    score: 9,
    img: "9_of_diamonds.png",
  },
  {
    id: 35,
    name: "9_of_hearts",
    score: 9,
    img: "9_of_hearts.png",
  },
  {
    id: 36,
    name: "9_of_spades",
    score: 9,
    img: "9_of_spades.png",
  },
  {
    id: 37,
    name: "10_of_clubs",
    score: 10,
    img: "10_of_clubs.png",
  },
  {
    id: 38,
    name: "10_of_diamonds",
    score: 10,
    img: "10_of_diamonds.png",
  },
  {
    id: 39,
    name: "10_of_hearts",
    score: 10,
    img: "10_of_hearts.png",
  },
  {
    id: 40,
    name: "10_of_spades",
    score: 10,
    img: "10_of_spades.png",
  },
  {
    id: 41,
    name: "jack_of_clubs",
    score: 10,
    img: "jack_of_clubs2.png",
  },
  {
    id: 42,
    name: "jack_of_diamonds",
    score: 10,
    img: "jack_of_diamonds2.png",
  },
  {
    id: 43,
    name: "jack_of_hearts",
    score: 10,
    img: "jack_of_hearts2.png",
  },
  {
    id: 44,
    name: "jack_of_spades",
    score: 10,
    img: "jack_of_spades2.png",
  },
  {
    id: 45,
    name: "king_of_clubs",
    score: 10,
    img: "king_of_clubs2.png",
  },
  {
    id: 46,
    name: "king_of_diamonds",
    score: 10,
    img: "king_of_diamonds2.png",
  },
  {
    id: 47,
    name: "king_of_hearts",
    score: 10,
    img: "king_of_hearts2.png",
  },
  {
    id: 48,
    name: "king_of_spades",
    score: 10,
    img: "king_of_spades2.png",
  },
  {
    id: 49,
    name: "queen_of_clubs",
    score: 10,
    img: "queen_of_clubs2.png",
  },
  {
    id: 50,
    name: "queen_of_diamonds",
    score: 10,
    img: "queen_of_diamonds2.png",
  },
  {
    id: 51,
    name: "queen_of_hearts",
    score: 10,
    img: "queen_of_hearts2.png",
  },
  {
    id: 52,
    name: "queen_of_spades",
    score: 10,
    img: "queen_of_spades2.png",
  },
];
